sudo: required
language: java

services:
  - docker

before_install:
  - mvn -N io.takari:maven:wrapper
  - mvn clean package

install:

before_script:

script:
  - docker build -t cyjay96/pipeline-one-docker-container

after_script:

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cyjay96/pipeline-one-docker-container

after_failure:

#deploy:
#  provider: elasticbeanstalk
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  region: eu-central-1
#  app: konstantin-pipeline-test
#  env: Konstantinpipelinetest-env
#  bucket_name: elasticbeanstalk-eu-central-1-953923509938
#  bucket_path: konstantin-pipeline-test
#  on:
#    branch: main
